"""Force-surrogate prep for the Track B program (see ``docs/force_surrogate/roadmap.md``).

Provides the single source of force/moment-coefficient normalization, a dimensionless
units-sidecar convention, a provenance wrapper that pins the Docker image digest, the
Aedes-anchored kinematic sweep generator (PR2), the forces-to-tidy-dataset extractor
(PR4: ``build_dataset``/``write_dataset``/``build_run_metadata``), and the PhysicsNeMo
kinematics(+phase) -> force-coefficient surrogate trainer (PR5: ``run_training`` plus the
torch-free feature/split/metrics helpers).
"""

from mosquito_cfd.force_surrogate.dataset import (
    build_dataset,
    build_run_metadata,
    load_manifest_configs,
    write_dataset,
)
from mosquito_cfd.force_surrogate.evidence_figure import (
    CFD_SECONDS_PER_WINGBEAT,
    MOMENT_PANEL,
    PANEL_COEFFICIENTS,
    KinematicParams,
    build_caption,
    build_figure,
    compute_speedup,
    generate_evidence_figure,
    lift_coefficient_dickinson,
    panel_annotation,
    parse_config_name,
    sane_dickinson_cf_z,
)
from mosquito_cfd.force_surrogate.normalization import (
    ForceCoefficients,
    ForceReference,
    MomentCoefficients,
    MomentReference,
    compute_force_coefficients,
    compute_force_reference,
    compute_moment_coefficient,
    compute_moment_reference,
)
from mosquito_cfd.force_surrogate.run_one_config import run_config
from mosquito_cfd.force_surrogate.runner import (
    Completion,
    ExecResult,
    RunOutcome,
    build_probe_command,
    build_run_command,
    build_wsl_command,
    capture_compute_hardware,
    check_completion,
    run_sweep,
)
from mosquito_cfd.force_surrogate.sidecar import (
    UNITS_VOCABULARY,
    capture_surrogate_run_metadata,
    read_units_sidecar,
    validate_image_digest,
    write_units_sidecar,
)
from mosquito_cfd.force_surrogate.sweep import (
    build_kinematic_grid,
    compute_reynolds,
    derive_run_duration,
    generate_sweep,
    render_inputs,
    select_holdout,
)
from mosquito_cfd.force_surrogate.train import (
    FEATURE_COLUMNS,
    TARGET_COLUMNS,
    SplitAssignment,
    Standardizer,
    build_features,
    build_metrics,
    build_model,
    build_predictions_frame,
    build_training_metadata,
    compute_config_resolved,
    compute_metrics,
    filter_converged_beat,
    filter_converged_beat_report_holdout,
    log_to_wandb,
    make_config_splits,
    predict,
    run_training,
    train_model,
)

__all__ = [
    "CFD_SECONDS_PER_WINGBEAT",
    "MOMENT_PANEL",
    "PANEL_COEFFICIENTS",
    "KinematicParams",
    "build_caption",
    "build_figure",
    "compute_speedup",
    "generate_evidence_figure",
    "lift_coefficient_dickinson",
    "panel_annotation",
    "parse_config_name",
    "sane_dickinson_cf_z",
    "ForceCoefficients",
    "ForceReference",
    "MomentCoefficients",
    "MomentReference",
    "compute_force_coefficients",
    "compute_force_reference",
    "compute_moment_coefficient",
    "compute_moment_reference",
    "build_dataset",
    "build_run_metadata",
    "load_manifest_configs",
    "write_dataset",
    "UNITS_VOCABULARY",
    "capture_surrogate_run_metadata",
    "read_units_sidecar",
    "validate_image_digest",
    "write_units_sidecar",
    "build_kinematic_grid",
    "compute_reynolds",
    "derive_run_duration",
    "generate_sweep",
    "render_inputs",
    "select_holdout",
    "Completion",
    "ExecResult",
    "RunOutcome",
    "build_probe_command",
    "build_run_command",
    "build_wsl_command",
    "capture_compute_hardware",
    "check_completion",
    "run_config",
    "run_sweep",
    "FEATURE_COLUMNS",
    "TARGET_COLUMNS",
    "SplitAssignment",
    "Standardizer",
    "build_features",
    "build_metrics",
    "build_model",
    "build_predictions_frame",
    "build_training_metadata",
    "compute_config_resolved",
    "compute_metrics",
    "filter_converged_beat",
    "filter_converged_beat_report_holdout",
    "log_to_wandb",
    "make_config_splits",
    "predict",
    "run_training",
    "train_model",
]
